CREATE TABLE IF NOT EXISTS Tiendas (

NombreTienda TEXT UNIQUE NOT NULL,
Capital INTEGER NOT NULL,
Horario TEXT NOT NULL,
Ubicacion TEXT ,
Categoria TEXT,
PRIMARY KEY (NombreTienda)

);


CREATE TABLE IF NOT EXISTS Clientes (

"e-mail " TEXT UNIQUE NOT NULL PRIMARY KEY,
Nombre TEXT ,
Apellido TEXT,
Direccion TEXT

);

CREATE TABLE IF NOT EXISTS Marcas(
IdMarca INTEGER UNIQUE NOT NULL  PRIMARY KEY AUTOINCREMENT,
NombreMarca TEXT UNIQUE NOT NULL,
NombreTienda TEXT UNIQUE NOT NULL,

FOREIGN KEY (NombreTienda) REFERENCES Tiendas (NombreTienda)
);


CREATE TABLE IF NOT EXISTS Articulos(

IdArt INTEGER NOT NULL UNIQUE  PRIMARY KEY AUTOINCREMENT,
Categoria TEXT NOT NULL,
Color TEXT NOT NULL,
Sexo NUMERIC NOT NULL,
Precio INTEGER NOT NULL,
IdMarca INTEGER NOT NULL UNIQUE,
Campaña TEXT,
FOREIGN KEY (IdMarca) REFERENCES Marcas ( IdMarca)

);


CREATE TABLE IF NOT EXISTS Empleados (
"IdEmpleado "INTEGER UNIQUE NOT NULL PRIMARY KEY AUTOINCREMENT,
"Tipo" TEXT UNIQUE NOT NULL,
"NombreTienda" TEXT,

FOREIGN KEY (NombreTienda) REFERENCES Tiendas (NombreTienda)

);
